### ISSUE TITLE
Symbiflow_synth : "-- Parsing `counter.v' using frontend ` -vlog2k' -- ERROR: Can't open input file `counter.v' for reading: No such file or directory

### ISSUE THREAD

**Issue by YCin** [chipsalliance/f4pga-examples#294]
Hi
When i try to test the example counter_test of X-ray project inside the board Artix7 35tcsg324-1 i have the following error 
-- Parsing `counter.v' using frontend ` -vlog2k' --
ERROR: Can't open input file `counter.v' for reading: No such file or directory

are there any one have suggestions fro this problem.

Thanks

**Comment by YCin** [comment]
symbiflow_write_bitstream -d artix7 -f top.fasm -p xc7a35tcpg236-1 -b example.bit
Writing bitstream ...
Traceback (most recent call last):
  File "/home/gg/opt/f4pga/xc7/conda/envs/xc7/bin/xcfasm", line 8, in <module>
    sys.exit(main())
  File "/home/gg/opt/f4pga/xc7/conda/envs/xc7/lib/python3.7/site-packages/xc_fasm/xc_fasm.py", line 63, in main
    emit_pudc_b_pullup=args.emit_pudc_b_pullup)
  File "/home/gg/opt/f4pga/xc7/conda/envs/xc7/lib/python3.7/site-packages/xc_fasm/fasm2frames.py", line 186, in fasm2frames
    assembler.parse_fasm_filename(filename_in, extra_features=extra_features)
  File "/home/gg/opt/f4pga/xc7/conda/envs/xc7/lib/python3.7/site-packages/prjxray/fasm_assembler.py", line 183, in parse_fasm_filename
    for line in fasm.parse_fasm_filename(filename):
  File "/home/gg/opt/f4pga/xc7/conda/envs/xc7/lib/python3.7/site-packages/fasm/parser/antlr.py", line 115, in parse_fasm_filename
    raise error[0]
Exception: Parse error at 0:0 - Couldn't open file
